# Generated by Django 5.1.7 on 2025-03-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timer',
            field=models.CharField(default='10:00', max_length=255),
        ),
    ]
