# Generated by Django 5.1.7 on 2025-04-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_video_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('location', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
