# Generated by Django 5.1.7 on 2025-04-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_glasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
