# Generated by Django 5.1.7 on 2025-04-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_glasses_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glasses',
        ),
    ]
