# Generated by Django 5.1.7 on 2025-04-22 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_glasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название локации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('image', models.ImageField(upload_to='movies/images')),
                ('film_id', models.CharField(max_length=255, verbose_name='id фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='MovieView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время просмотра')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_views', to='users.location', verbose_name='Локация')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Просмотр фильма',
                'verbose_name_plural': 'Просмотры фильмов',
            },
        ),
    ]
