# Generated by Django 5.1.7 on 2025-04-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_location_movie_movieview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
    ]
