# Generated by Django 5.1.7 on 2025-04-22 14:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieViewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2025, 4, 22), verbose_name='Дата')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='Локация')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Счетчик просмотров фильма',
                'verbose_name_plural': 'Счетчики просмотров фильмов',
                'unique_together': {('location', 'movie', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='MovieView',
        ),
    ]
