# Generated by Django 5.1.3 on 2025-02-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(default='tuva', max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('year', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('route_id', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('serial', models.BooleanField()),
                ('isAdded', models.BooleanField()),
                ('series', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category_images/')),
                ('name_short', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(default='Описание', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('name_short', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=200)),
                ('serial', models.BooleanField()),
                ('isAdded', models.BooleanField()),
                ('image', models.ImageField(upload_to='movie_images/')),
                ('time', models.CharField(default='10', help_text='Введите длительность фильма', max_length=20)),
                ('format', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=100, help_text='Укажите цену')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.category')),
            ],
        ),
    ]
