# Generated by Django 5.1.3 on 2025-02-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_category_number_alter_category_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='Описание', max_length=400),
        ),
    ]
