# Generated by Django 5.1.3 on 2025-02-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_movie_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.BooleanField(default=True),
        ),
    ]
