# Generated by Django 5.1.3 on 2025-03-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_movie_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='backImg',
            field=models.ImageField(blank=True, null=True, upload_to='back_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='backImg',
            field=models.ImageField(blank=True, null=True, upload_to='back_movie_images/'),
        ),
    ]
