# Generated by Django 5.1.3 on 2025-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_category_backimg_movie_backimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='queueImg',
            field=models.ImageField(blank=True, null=True, upload_to='back_movie_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='queueImg',
            field=models.ImageField(blank=True, null=True, upload_to='back_movie_images/'),
        ),
    ]
