# Generated by Django 5.1.3 on 2025-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_category_queueimg_movie_queueimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='queueImg',
            field=models.ImageField(blank=True, null=True, upload_to='queue_category_mages/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='queueImg',
            field=models.ImageField(blank=True, null=True, upload_to='queue_movie_images/'),
        ),
    ]
