# Generated by Django 5.1.3 on 2025-03-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_category_description_alter_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('order_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(default='created', max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
