# Generated by Django 5.2 on 2025-04-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('client_id', 'location')},
        ),
    ]
